# SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# NVIDIA NeMo Agent Toolkit 黑客松配置
# 支持用户自定义OpenAI兼容API

general:
  use_uvloop: true

functions:
  internet_search:
    _type: tavily_internet_search
    description: "使用Tavily API进行实时网络搜索"
  
  # current_datetime:
  #   _type: current_datetime
  #   description: "获取当前日期和时间"

  add_item_tool:
    _type: mcp_tool_wrapper
    url: "http://localhost:8000/mcp"
    transport: "streamable-http"
    mcp_tool_name: add_item_tool
    description: "添加物品记录：物品的详细描述，包括名称、数量、位置等信息"

  search_items_tool:
    _type: mcp_tool_wrapper
    url: "http://localhost:8000/mcp"
    transport: "streamable-http"
    mcp_tool_name: search_items_tool
    description: "语义化搜索物品"

  list_all_items_tool:
    _type: mcp_tool_wrapper
    url: "http://localhost:8000/mcp"
    transport: "streamable-http"
    mcp_tool_name: list_all_items_tool
    description: "列出所有物品记录"

  mcp_client:
    _type: mcp_client
    server:
      transport: streamable-http
      url: "http://localhost:8000/mcp"

llms:
  # 默认使用Bailian API (用户可修改)
  default_llm:
    _type: openai
    model_name: "qwen3:8b"
    api_key: "Your API Key"
    # base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    base_url: "http://localhost:11434/v1"
    temperature: 0.7
    max_tokens: 2048

workflow:
  _type: react_agent
  tool_names:
    - internet_search
    - current_datetime
    - add_item_tool
    - search_items_tool
    - list_all_items_tool
    - mcp_client
  llm_name: default_llm
  verbose: true
  parse_agent_response_max_retries: 3
  max_iterations: 10

